In [1]:
import numpy as np

In [3]:
array1D = np.array([10,15,14])
print(array1D)

[10 15 14]


In [4]:
array2D = np.array([[15, 30, 40], [15,10,81]])
print(array2D)

[[15 30 40]
 [15 10 81]]


In [5]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
ones = np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
